"""Utilities package for Audio-to-MIDI conversion."""

from .device import get_device, set_seed, get_device_info
from .audio import (
    load_audio,
    resample_audio,
    extract_features,
    detect_onsets,
    detect_pitch,
    apply_preemphasis,
    remove_preemphasis,
    compute_cmvn,
    apply_cmvn,
    chunk_audio,
)
from .midi import (
    NoteEvent,
    MIDISequence,
    hz_to_midi,
    midi_to_hz,
    quantize_time,
    create_midi_file,
    load_midi_file,
    merge_overlapping_notes,
    filter_notes_by_velocity,
    filter_notes_by_duration,
    quantize_notes,
    extract_chord_sequence,
    compute_polyphony_stats,
    validate_midi_notes,
)

__all__ = [
    "get_device",
    "set_seed", 
    "get_device_info",
    "load_audio",
    "resample_audio",
    "extract_features",
    "detect_onsets",
    "detect_pitch",
    "apply_preemphasis",
    "remove_preemphasis",
    "compute_cmvn",
    "apply_cmvn",
    "chunk_audio",
    "NoteEvent",
    "MIDISequence",
    "hz_to_midi",
    "midi_to_hz",
    "quantize_time",
    "create_midi_file",
    "load_midi_file",
    "merge_overlapping_notes",
    "filter_notes_by_velocity",
    "filter_notes_by_duration",
    "quantize_notes",
    "extract_chord_sequence",
    "compute_polyphony_stats",
    "validate_midi_notes",
]
